Fix broken website.
+ Error: "Uncaught TypeError: L.control.locate is not a function"
+ Revert "build(deps): bump leaflet.locatecontrol from 0.81.1 to 0.82.0"
+ This reverts commit 8f31e14c491ba4d1abb8bdc8b314b362f49bca5a.